# Setting up automatic travis test build.

branches:
  only:
  - master
  - dev

language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - if [[ `python3 -c 'import sys ; print(".".join([str(i) for i in sys.version_info[:][:2]]))'` == '3.5' ]]; then pip3 install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp35-cp35m-linux_x86_64.whl; fi
  - if [[ `python3 -c 'import sys ; print(".".join([str(i) for i in sys.version_info[:][:2]]))'` == '3.6' ]]; then pip3 install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp36-cp36m-linux_x86_64.whl; fi
  - pip3 install -r requirements.txt
# command to run tests
script:
  - python setup.py install
  # pytest
