# Setting up automatic travis test build.
sudo: required
branches:
  only:
  - master
  - dev

services:
  - docker

env:
  - VERSION=$(cat setup.py| grep version | tail -c 8 | cut -c 1-5)

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker pull divkal/cdt-env-base:1.0
      - docker build --build-arg python=3.6 -t divkal/cdt-py3.6:$VERSION .
    - stage: test
      script: docker run --rm divkal/cdt /bin/sh -c 'cd /CDT && pytest --cov && codecov -t $CODECOV_TOKEN'
    - stage: deploy
      script:
      - docker push divkal/cdt-py3.6:$VERSION
    - script:
      - docker build --build-arg python=3.7 -t divkal/cdt-py3.7:$VERSION .
      - docker push divkal/cdt-py3.7:$VERSION
    - script:
      - docker pull divkal/nv-cdt-env-base:1.0
      - docker build -f nv-Dockerfile -t divkal/nv-cdt-py3.6:$VERSION .
      - docker push divkal/nv-cdt-py3.6:$VERSION .
